---
# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # To update all the images in the operatorconfig and tests/e2e/testfiles directory
  - package-ecosystem: "docker"
    directories:
      # Update the version to latest post release to stay up to date
      - "/operatorconfig/driverconfig/powerflex/v2.15.0/**"
      - "/operatorconfig/driverconfig/powermax/v2.15.0/**"
      - "/operatorconfig/driverconfig/powerscale/v2.15.0/**"
      - "/operatorconfig/driverconfig/powerstore/v2.15.0/**"
      - "/operatorconfig/driverconfig/unity/v2.15.0/**"
      - "/samples/v2.15.0/**/**"
      - "/tests/e2e/testfiles/**"
      - "/testdata/default.yaml"
      - "/operatorconfig/driverconfig/common/default.yaml"
      - "/config/samples/storage_v1_csm_powerflex.yaml"
      - "/config/samples/storage_v1_csm_powermax.yaml"
      - "/config/samples/storage_v1_csm_powerscale.yaml"
      - "/config/samples/storage_v1_csm_powerstore.yaml"
      - "/config/samples/storage_v1_csm_unity.yaml"
    schedule:
      interval: "daily"
    target-branch: "main"
    groups:
      updates:
        patterns:
          - "*"
